# Generated by Django 3.2 on 2023-04-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_text_comment_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
