# Generated by Django 3.2 on 2023-04-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_title_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='raiting',
            field=models.FloatField(),
        ),
    ]
