# Generated by Django 3.2.16 on 2023-04-19 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230419_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MaxLengthValidator(256)]),
        ),
    ]
