# Generated by Django 3.2 on 2023-04-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(error_messages={'unique': 'Год не может быть в будущем или отрицательным.'}, verbose_name='Год выхода'),
        ),
    ]
