# Generated by Django 3.2 on 2023-05-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='title',
            name='year_lte_current_year',
        ),
        migrations.RemoveConstraint(
            model_name='title',
            name='year_gte_minimum_year',
        ),
    ]
